### ISSUE TITLE
Add instructions for the demo

### ISSUE THREAD

**Issue by baraklevyy** [evandiewald/rto-token#1]
Hi,

I'm facing difficulties running and demo your code by myself, can you please add a guide on how to run the code and use a demo?

**Comment by evandiewald** [comment]
Hi @baraklevyy, thanks for checking out the demo! I apologize that the documentation is lacking - I'll try to provide a step-by-step guide in the next week or so. 

In the meantime, I assume you have already checked out the project blog [here](https://towardsdatascience.com/creating-an-ethereum-token-to-enable-a-decentralized-rent-to-own-network-cc3786cf1142)?

Could you also let me know exactly where you're running into issues? Is it with deploying the smart contract, the API, or something else?

**Comment by baraklevyy** [comment]
Hi
Thanks for the reply.
I'm getting problems with the postgreSQL for the application.
Also I find it difficult to deploy the contract, do I need to change the
parameters?

what is the INFURA_URL and if I have to change something there?
[image: image.png]

‫בתאריך שבת, 21 באוג׳ 2021 ב-22:18 מאת ‪Evan Diewald‬‏ <‪
***@***.***‬‏>:‬

**Comment by baraklevyy** [comment]
Also there is no way to charge the wallet for ETH with MetaMask and Ropsten.
I'm trying to use these faucets:
https://faucet.ropsten.be/
and
https://faucet.metamask.io/
But any attempt to withdraw some ETH was fruitless.


‫בתאריך שבת, 21 באוג׳ 2021 ב-22:29 מאת ‪Barak Levy‬‏ ***@***.***
‬‏>:‬

**Comment by baraklevyy** [comment]
so you can skip the previous mail regarding the faucets.

When we launch the website after the deployment we cannot enter "My
Balances" and "View Listings".
[image: image.png]

‫בתאריך שבת, 21 באוג׳ 2021 ב-22:42 מאת ‪Barak Levy‬‏ ***@***.***
‬‏>:‬

**Comment by baraklevyy** [comment]
Hi Evan,

Can you upload the instructions and or conduct a quick call with me to
start up the demo.

**Comment by baraklevyy** [comment]
Hi Evan,

I'm sorry to disturb you, my friend and I have the whole day tomorrow to
try to investigate how to run your demo.
I really invested many hours trying to solve that.
Is there any chance that you can send me instructions or make a zoom
meeting with me for 10 minutes help us understand what wrong with our
process.
I'm sorry to bother you.

Thank you very much,

Best, Barak

‫בתאריך שבת, 21 באוג׳ 2021 ב-22:18 מאת ‪Evan Diewald‬‏ <‪
***@***.***‬‏>:‬

**Comment by evandiewald** [comment]
@baraklevyy I'm sorry - I simply do not have the time to support this repository in any formal way. It is meant as a supplementary startup guide with a focus on executing smart contract functions with Python, but it utilizes other resources (like Postgres, FastAPI, and MetaMask) that others can detail more specifically. There are many great resources out there that may provide the step-by-step assistance that you're looking for:

Ethereum for Python Developers: https://www.dappuniversity.com/articles/web3-py-intro (this may be a better place for you to start, rather than my demo)
FastAPI: https://fastapi.tiangolo.com/
Sending transactions with MetaMask: https://docs.metamask.io/guide/sending-transactions.html#example
Postgres with Python: https://www.postgresqltutorial.com/postgresql-python/

I am going to close this issue because it is lacking specificity. If you have a problem with something particular, please provide the Error message and additional details about what you were trying to do when you encountered the bug. Like I said, I cannot provide open-ended guidance, but it will be easier to help with specific problems.
